import type { Metadata } from "next";
import "../style/globals.css"
import 'react-toastify/dist/ReactToastify.css';
import "react-responsive-carousel/lib/styles/carousel.min.css";
import Layout from "@/UI/Layout";



export const metadata: Metadata = {
  title: "Buy Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className=" font-MainFont bg-[#E3E6E6]">
             <Layout>{children} </Layout>
        </body>
    </html>
  );
}
